version: "3.9"

services:
  db:
    image: postgres:15.0-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - users_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

  auth_service:
    build:
      context: ./ui
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"


volumes:
  users_data:
  static:

